server:
  port: ${PORT:8080}

spring:
  application:
    name: talis-dictionary

  thymeleaf:
    prefix: classpath:/classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

unsplash:
  access-key: "L2nkNANBwps0OHTcVOkmwC5pTWO7q9ok_atwDg2v8Pw"
  api-url: https://api.unsplash.com/search/photos
